GET http://localhost:3000/
###
GET http://localhost:3000/api/users/id
x-access-token: 
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name":"sourav Manna",
    "email":"Sourav@gmail.com",
    "address":"Bangalore"
}

###
PATCH  http://localhost:3000/api/users/id
Content-Type: application/json
x-access-token:

{
    "address":"Chittaranjan"
}

#####
DELETE   http://localhost:3000/api/users/id
x-access-token:
